#!/bin/ksh
#
# $OpenBSD: mysqld.rc,v 1.6 2020/07/07 12:40:45 sthen Exp $

daemon="/usr/local/bin/daemon"
daemon_flags="-u _mysql /usr/local/libexec/mariadbd"

. /etc/rc.d/rc.subr

mkdir -p /var/run/mysql
chown _mysql:_mysql /var/run/mysql

rc_bg=YES
rc_reload=NO

rc_cmd $1
