TEMPLATE = ../bin/adm-template

x:

copy: x ${COPY}
	mkdir -p /etc/${NAME}
	cp -rf ${COPY} /etc/${NAME}

conf: x ${CONF:=.in} /etc/${NAME}/${CONF}

/etc/${NAME}/${CONF}: x Makefile ${CONF:=.in} ${TEMPLATE}
	mkdir -p ${@D}
	${TEMPLATE} ${CONF:=.in} -- ${ENV} >/tmp/adm-etc-conf
	mv -f /tmp/adm-etc-conf $@
