#!/bin/sh -eu
: ${timeout:=1}
: ${time:=30}

q="
	SELECT ID FROM INFORMATION_SCHEMA.PROCESSLIST
		WHERE Time > $time
	AND	Command != 'Sleep'
"

exec [ -z "$(exec timeout "$timeout" mysql -Be "$q")" ]
