# by {{ path }} at {{ date }}

[irc]
[irc.local]
  Server = "127.0.0.1:6667"
  Nick = "matterbridge"
  RemoteNickFormat = "<{NICK}> "

[whatsapp]
[whatsapp.me]
  Number = "{{ db/whatsapp-var:tel }}"
  SessionFile = "/var/cache/matterbridge/whatsapp.gob"

[discord]
[discord.me]
  Token = "{{ db/discord-var:token }}"
  Server = "{{ db/discord-var:guild }}"

# whatsapp chans
#for db/whatsapp-chan

[[gateway]]
  name = "#whatsapp-{{ 1:name }}"
  enable = true
[[gateway.inout]]
  account = "irc.local"
  channel = "#whatsapp-{{ 1:name }}"
  options = { key="{{ db/irc_chan:pass name=#whatsapp-[1:name] }}" }
[[gateway.inout]]
  account = "whatsapp.me"
  channel = "{{ 1:name }}"
#end

# discord chans
#for db/discord-chan

[[gateway]]
  name = "#discord-{{ 1:name }}"
  enable = true
[[gateway.inout]]
  account = "irc.local"
  channel = "#discord-{{ 1:name }}"
  options = { key="{{ db/irc-chan:pass name=#discord-[1:name] }}" }
[[gateway.inout]]
  account = "discord.me"
  channel = "{{ 1:name }}"
#end
